###########自定义##########
ip: http://47.97.91.13:8081/
imageSavePath: /home/web/course-selection/image/
imageVisitPath: ${ip}static/image/

##########配置#################
server:
  port: 8081
spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: file:/home/web/course-selection/
  redis:
    password: ZIB12584884

#日志打印位置
logging:
  file:
    name: /home/web/course-selection/course-selection.log


